# Generated by Django 4.2.3 on 2023-07-10 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('backoffice', 'Backoffice'), ('design', 'Design'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('media', 'Media')], default='design', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('inProgress', 'In progress'), ('toDo', 'To-do'), ('awaitingFeedback', 'Awaiting feedback'), ('done', 'Done')], default='toDo', max_length=20)),
                ('assignee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
