# Generated by Django 5.0 on 2023-12-30 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 30, 10, 53, 20, 942384, tzinfo=datetime.timezone.utc)),
        ),
    ]
